version: "3.9"  # optional since v1.27.0
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: "/bin/sh -c 'air'"
    ports:
      - "8080:8080"
    environment:
      APP_ENV: docker
    volumes:
      - .:/app
    networks:
      vps_network:
    depends_on:
      - mysql
      - postgres
      - mailhog
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=auth
    volumes:
      - 'mysql_db:/var/lib/mysql'
    networks:
      vps_network:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_MULTIPLE_DATABASES=auth,user
    volumes:
      - 'postgres_db:/var/lib/postgresql/data/'
      - '.db_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql'
    networks:
      vps_network:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'  # SMTP port
      - '8025:8025'  # Web UI port
    networks:
      vps_network:
volumes:
  mysql_db:
  postgres_db:

networks:
  vps_network:
