package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"

	"github.com/weeb-vip/auth/graph/generated"
	"github.com/weeb-vip/auth/graph/model"
	"github.com/weeb-vip/auth/internal/resolvers"
)

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.RegisterResult, error) {
	return resolvers.Register(ctx, &r.Config, r.CredentialService, r.ValidationToken, r.MailService, input.Username, input.Password)
}

// CreateSession is the resolver for the CreateSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, input *model.LoginInput) (*model.SigninResult, error) {
	return resolvers.CreateSession(ctx, r.CredentialService, r.SessionService, r.RefreshTokenService, r.JwtTokenizer, input)
}

// RequestPasswordReset is the resolver for the RequestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input model.RequestPasswordResetInput) (bool, error) {
	return resolvers.RequestPasswordReset(ctx, r.CredentialService, r.PasswordResetService, r.MailService, &r.Config, input.Username, input.Email)
}

// ResetPassword is the resolver for the ResetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPasswordInput) (bool, error) {
	return resolvers.ResetPassword(ctx, r.CredentialService, r.PasswordResetService, input.Token, input.Username, input.NewPassword)
}

// RefreshToken is the resolver for the RefreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.SigninResult, error) {
	return resolvers.RefreshToken(ctx, r.SessionService, r.RefreshTokenService, r.JwtTokenizer, token)
}

// VerifyEmail is the resolver for the VerifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context) (bool, error) {
	return resolvers.EmailVerification(ctx, r.CredentialService, r.UserProducer)
}

// ResendVerificationEmail is the resolver for the ResendVerificationEmail field.
func (r *mutationResolver) ResendVerificationEmail(ctx context.Context, username string) (bool, error) {
	return resolvers.ResendVerificationEmail(ctx, r.CredentialService, r.ValidationToken, r.MailService, &r.Config, username)
}

// AvailabilityByUsername is the resolver for the availabilityByUsername field.
func (r *queryResolver) AvailabilityByUsername(ctx context.Context, username string) (bool, error) {
	// this one will be converted to use dataloader in next release
	return resolvers.AvailabilityByUsername(ctx, r.CredentialService, username)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
