package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"

	"github.com/weeb-vip/auth/graph/generated"
	"github.com/weeb-vip/auth/graph/model"
	"github.com/weeb-vip/auth/internal/resolvers"
)

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.RegisterResult, error) {
	return resolvers.Register(ctx, r.CredentialService, r.ValidationToken, r.UserClient, r.Config, input.Firstname, input.Lastname, input.Username, input.Password, string(input.Language))
}

// CreateSession is the resolver for the CreateSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, input *model.LoginInput) (*model.SigninResult, error) {
	return resolvers.CreateSession(ctx, r.CredentialService, r.SessionService, r.RefreshTokenService, r.JwtTokenizer, input)
}

// RequestPasswordReset is the resolver for the RequestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input model.RequestPasswordResetInput) (bool, error) {
	return resolvers.RequestPasswordReset(ctx, r.CredentialService, r.PasswordResetService, input.Username)
}

// AvailabilityByUsername is the resolver for the availabilityByUsername field.
func (r *queryResolver) AvailabilityByUsername(ctx context.Context, username string) (bool, error) {
	// this one will be converted to use dataloader in next release
	return resolvers.AvailabilityByUsername(ctx, r.CredentialService, username)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) UserInfo(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UserInfo - userInfo"))
}
*/
