package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"

	"github.com/weeb-vip/auth/graph/generated"
	"github.com/weeb-vip/auth/graph/model"
)

// ActiveSessions is the resolver for the active_sessions field.
func (r *userResolver) ActiveSessions(ctx context.Context, obj *model.User) ([]*model.SessionDetails, error) {
	// while actually implementing this, a dataloader will be a must-have.
	// when we have a Repository which can give session details based on user, we use that.
	return []*model.SessionDetails{}, nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
